rule1:
	mpicc -O3  -o MPI_PSRS  /home/ubuntu/test/MPI_PSRS.c
	scp MPI_PSRS  ubuntu@10.2.10.132:/home/ubuntu/test/
	scp MPI_PSRS  ubuntu@10.2.11.132:/home/ubuntu/test/
	scp MPI_PSRS  ubuntu@10.2.12.132:/home/ubuntu/test/

